name: Windows build
on:
  push:
    tags:
      - '*'
      paths:
        - ".github/workflows/*"
        - "src/*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [devel]

    name: 'Nim ${{ matrix.branch }}'
    runs-on: windows-latest

    defaults:
      run:
        working-directory: minmax-tictactoe

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: minmax-tictactoe

      - name: Setup mingw
        uses: egor-tensin/setup-mingw@v1

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.branch }}

      - name: Get SDL
        run: nimble deps

      - name: Install dependencies
        run: nimble install -y --depsOnly

      - name: Compile release build
        run: nimble release

      - name: Upload release
        uses: meeDamian/github-release@2.0
        with:
          name: Windows Build
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            tictactoe.exe
            SDL2.dll